apiVersion: v1
data:
  app-config.yaml: |
    app:
      baseUrl: https://backstage-developer-hub.apps.home.myocp.net
    auth:
      environment: production
      providers:
        oauth2Proxy: {}
    backend:
      auth:
        keys:
        - secret: u95WN24xnXu7OUQL5ji1qAAVC3TF9Re6
      baseUrl: https://backstage-developer-hub.apps.home.myocp.net
      cors:
        origin: https://backstage-developer-hub.apps.home.myocp.net
      database:
        client: pg
        connection:
          host: 'backstage-db-postgresql'
          password: ${POSTGRESQL_ADMIN_PASSWORD}
          port: 5432
          ssl:
            ca: ${CA_CERT}
            rejectUnauthorized: true
            require: true
          user: postgres
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      locations:
      - target: https://github.com/idp-myocp/backstage-showcase/blob/main/catalog-entities/all.yaml
        type: url
      - target: https://github.com/idp-myocp/goldenpath-template/blob/main/template-index.yaml
        type: url
      providers:
        github:
          systemEntities:
            catalogPath: /catalog-info.yaml
            filters:
              branch: master
              repository: .*
            organization: idp-myocp
            schedule:
              frequency:
                minutes: 1
              initialDelay:
                seconds: 15
              timeout:
                minutes: 1
          systems:
            catalogPath: /systems/*.yaml
            filters:
              branch: main
              repository: demo-systems
            organization: idp-myocp
            schedule:
              frequency:
                minutes: 1
              initialDelay:
                seconds: 15
              timeout:
                minutes: 1
        keycloakOrg:
          default:
            baseUrl: 'https://sso.myocp.net'
            clientId: 'backstage'
            clientSecret: 'qvUbt9vPnjiVBjSeFSU71YgObxUaezxZ'
            loginRealm: 'backstage'
            realm: 'OpenShift'
            schedule:
              frequency:
                minutes: 1
              initialDelay:
                seconds: 15
              timeout:
                minutes: 1
      rules:
      - allow:
        - Component
        - System
        - Group
        - Resource
        - Location
        - Template
        - API
    integrations:
      github:
      - host: github.com
        token: '7de38a5e47149d0cf79057a3be76a0132d63be56'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"app-config.yaml":"app:\n  baseUrl: https://backstage-developer-hub.apps.home.myocp.net\nauth:\n  environment: production\n  providers:\n    oauth2Proxy: {}\nbackend:\n  auth:\n    keys:\n    - secret: u95WN24xnXu7OUQL5ji1qAAVC3TF9Re6\n  baseUrl: https://backstage-developer-hub.apps.home.myocp.net\n  cors:\n    origin: https://backstage-developer-hub.apps.home.myocp.net\n  database:\n    client: pg\n    connection:\n      host: 'backstage-db-postgresql'\n      password: ${POSTGRESQL_ADMIN_PASSWORD}\n      port: 5432\n      ssl:\n        ca: ${CA_CERT}\n        rejectUnauthorized: true\n        require: true\n      user: postgres\ncatalog:\n  import:\n    entityFilename: catalog-info.yaml\n    pullRequestBranchName: backstage-integration\n  locations:\n  - target: https://github.com/idp-myocp/backstage-showcase/blob/main/catalog-entities/all.yaml\n    type: url\n  - target: https://github.com/idp-myocp/goldenpath-template/blob/main/template-index.yaml\n    type: url\n  providers:\n    github:\n      systemEntities:\n        catalogPath: /catalog-info.yaml\n        filters:\n          branch: master\n          repository: .*\n        organization: idp-myocp\n        schedule:\n          frequency:\n            minutes: 1\n          initialDelay:\n            seconds: 15\n          timeout:\n            minutes: 1\n      systems:\n        catalogPath: /systems/*.yaml\n        filters:\n          branch: main\n          repository: demo-systems\n        organization: idp-myocp\n        schedule:\n          frequency:\n            minutes: 1\n          initialDelay:\n            seconds: 15\n          timeout:\n            minutes: 1\n    keycloakOrg:\n      default:\n        baseUrl: 'https://sso.myocp.net'\n        clientId: 'backstage'\n        clientSecret: 'qvUbt9vPnjiVBjSeFSU71YgObxUaezxZ'\n        loginRealm: 'backstage'\n        realm: 'OpenShift'\n        schedule:\n          frequency:\n            minutes: 1\n          initialDelay:\n            seconds: 15\n          timeout:\n            minutes: 1\n  rules:\n  - allow:\n    - Component\n    - System\n    - Group\n    - Resource\n    - Location\n    - Template\n    - API\nintegrations:\n  github:\n  - host: github.com\n    token: '7de38a5e47149d0cf79057a3be76a0132d63be56'\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"backstage"},"name":"backstage-app-config","namespace":"developer-hub"}}
  creationTimestamp: "2023-12-05T14:38:04Z"
  labels:
    app.kubernetes.io/instance: backstage
  name: backstage-app-config
  namespace: developer-hub
  resourceVersion: "624110651"
  uid: 6c5bfbf2-9d26-4c72-af66-a6ffdf1be4a7
