kind: AppProject
apiVersion: argoproj.io/v1beta1
metadata:
  name: argocd-developers
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'
