apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/idp-myocp/platform-components.git
    path: argocd/platform-applications
    targetRevision: main
    helm:
      parameters:
        - name: gitOrg
          value: https://github.com/idp-myocp
        - name: gitRef
          value: main
        - name: clusterBaseUrl
          value: XXX.XXXX.XXXXX
        - name: "backstage.githubToken"
          value: ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        - name: "backstage.db.adminPassword"
          value: backstage-postgres-admin-passwd
        - name: "keycloak.backstageClient.secret"
          value: CjrBujp80h6lWt7PEesM4tklZaqTfPal
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true       
    retry:
      limit: 0 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
