apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitOrg }}/platform-components.git"
    path: backstage-helm
    targetRevision: "{{ .Values.gitRef }}"
    helm:
      parameters:
        - name: "global.clusterRouterBase"
          value: "apps.{{ .Values.clusterBaseUrl }}"
        - name: "global.cluster.token"
          value: "{{ .Values.backstage.cluster.token }}"
        - name: "global.argocd.username"
          value: "{{ .Values.backstage.argoUsername }}"
        - name: "global.argocd.password"
          value: "{{ .Values.backstage.argoPassword }}"
        - name: "global.argocd.token"
          value: "{{ .Values.backstage.argoToken }}"
        - name: "global.github.token"
          value: "{{ .Values.backstage.githubToken }}"
        - name: "global.github.appId"
          value: "{{ .Values.backstage.githubAppId }}"
        - name: "global.github.oauthClientId"
          value: "{{ .Values.backstage.githubClientId }}"
        - name: "global.github.oauthClientSecret"
          value: "{{ .Values.backstage.githubClientSecret }}"
        - name: "global.github.clientId"
          value: "{{ .Values.backstage.githubClientId }}"
        - name: "global.github.clientSecret"
          value: "{{ .Values.backstage.githubClientSecret }}"
        - name: "global.github.webhookUrl"
          value: "{{ .Values.backstage.githubWebHookUrl }}"
        - name: "global.github.webhookSecret"
          value: "{{ .Values.backstage.githubWebHookSecret }}"
        - name: "global.keycloak.backstageClient.secret"
          value: "{{ .Values.keycloak.backstageClient.secret }}"
        - name: "global.backstage.atlassian.url"
          value: "{{ .Values.backstage.atlassian.url }}"
        - name: "global.backstage.atlassian.user"
          value: "{{ .Values.backstage.atlassian.user }}"
        - name: "global.backstage.atlassian.password"
          value: "{{ .Values.backstage.atlassian.password }}"
        - name: "global.backstage.jira.token"
          value: "{{ .Values.backstage.jira.token }}"
        - name: "global.jfrog.artifactory.url"
          value: "{{ .Values.jfrog.artifactory.url }}"
        - name: "global.jfrog.artifactory.token"
          value: "{{ .Values.jfrog.artifactory.token }}"
        - name: "global.sonar.token"
          value: "{{ .Values.backstage.sonar.token }}"
        - name: "global.sonar.url"
          value: "{{ .Values.backstage.sonar.url }}"
        - name: "global.lighthouse.url"
          value: "{{ .Values.lighthouse.url }}"

  destination:
    server: https://kubernetes.default.svc
    namespace: developer-hub
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m