apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-db
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitOrg }}/platform-components.git"
    path: postgresql-helm
    targetRevision: "{{ .Values.gitRef }}"
    helm:
      parameters:
        - name: "global.postgresql.auth.postgresPassword"
          value: "{{ .Values.backstage.db.adminPassword }}"
        - name: "tls.certificatesSecret"
          value: "backstage-db-postgresql-tls"
  destination:
    server: https://kubernetes.default.svc
    namespace: developer-hub
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
