apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitOrg }}/platform-components.git"
    path: backstage-helm
    targetRevision: "{{ .Values.gitRef }}"
    helm:
      parameters:
        - name: "global.clusterRouterBase"
          value: "apps.{{ .Values.clusterBaseUrl }}"
        - name: "global.github.token"
          value: "{{ .Values.backstage.githubToken }}"
        - name: "global.github.appId"
          value: "{{ .Values.backstage.githubAppId }}"
        - name: "global.github.clientId"
          value: "{{ .Values.backstage.githubClientId }}"
        - name: "global.github.clientSecret"
          value: "{{ .Values.backstage.githubClientSecret }}"
        - name: "global.github.webhookUrl"
          value: "{{ .Values.backstage.githubWebHookUrl }}"
        - name: "global.github.webhookSecret"
          value: "{{ .Values.backstage.githubWebHookSecret }}"
        - name: "global.github.privateKey"
          value: "{{ .Values.backstage.githubPrivateKey }}"

        - name: "global.keycloak.backstageClient.secret"
          value: "{{ .Values.keycloak.backstageClient.secret }}"
        - name: "global.backstage.confluence.url"
          value: "{{ .Values.backstage.confluence.url }}"
        - name: "global.backstage.confluence.user"
          value: "{{ .Values.backstage.confluence.user }}"
        - name: "global.backstage.confluence.password"
          value: "{{ .Values.backstage.confluence.password }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: developer-hub
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
