apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spectral-ci
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: "https://github.com/janus-api-idp/spectral-image.git"
    path: .tekton
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: spectral-ci
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
