apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: True
  profile: RHSSO
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: SSO_IMPORT_FILE
          value: /tmp/realms/realm-backstage.json
      volumes:
        items:
          - configMaps:
            - realm-backstage
            mountPath: /tmp/realms